name = "Example"
uuid = "e83e49e0-9c73-11ea-0f72-7b2612c12766"
authors = ["josePereiro"]
version = "0.3.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
